print("Me encanta estudiar python")
print('esto es lo "mismo"')
print("Hola" + " "'Fede')
print("me llamo  \"Gastón\"")
print("estas es un linea \n y estas es otra linea")
print("\testa es la tercera linea")
print('this ins´\'t a number')
print(' Línea 1\n Línea 2\n Línea 3')
print(' ' 'Línea 1\n Línea 2\n Línea 3')
print("A\tB\tC")
print("D\tE\tF")
print("G\tH\tI")
print("A\tB\tC\nD\tE\tF\nG\tH\tI")
print("Barra Normal: / \nBarra Invertida: \\")
print(input("ingresa tu nombre: "))
print( "Tu apellido es: " + input("ingresa tu apellido: "))
